[build]
builder = "NIXPACKS"
buildCommand = "npm run build"

[deploy]
startCommand = "npm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environments.production]
variables = { NODE_ENV = "production" }

[environments.staging]
variables = { NODE_ENV = "staging" }

[[environments.production.services]]
name = "veefore-app"
source = "."
variables = { PORT = "8080" }

[networking]
allowedHosts = ["veefore.com", "www.veefore.com"]