services:
  - type: web
    name: veefore-app
    env: node
    plan: starter
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    autoDeploy: false
    
databases:
  - name: veefore-mongodb
    plan: free
    
envVarGroups:
  - name: veefore-env
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: veefore-mongodb
          property: connectionString